platform :ios, '5.0'
# ignore all warnings from all pods
inhibit_all_warnings!
pod 'AFNetworking', '~> 1.3.3'
pod 'PSTCollectionView', '~> 1.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Godzippa', '~> 0.1.2'
pod 'HPGrowingTextView', '~> 1.0.1'